version: "3"

services:
  leaf2mqtt:
    container_name: leaf2mqtt
    image: ghcr.io/jvcaloen/leaf2mqtt:latest
    logging:
      options:
        max-size: "1M"
        max-file: "5"
    env_file:
      - local_settings.env
    restart: unless-stopped

